# Generated by Django 5.2.8 on 2025-11-17 17:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, help_text='Role or position at venue', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this venue')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['venue', '-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Denmark', max_length=100)),
                ('cvr_number', models.CharField(blank=True, max_length=50, verbose_name='CVR Number')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='e.g., IE001, IE032', max_length=20, unique=True, verbose_name='Contract Number')),
                ('contract_date', models.DateField(verbose_name='Contract Date')),
                ('concert_date', models.DateField(verbose_name='Concert Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('duration_minutes', models.IntegerField(default=75, help_text='e.g., 75 for 1x75min', verbose_name='Duration (minutes)')),
                ('encore_possible', models.BooleanField(default=True, verbose_name='Encore Possible')),
                ('location', models.CharField(blank=True, help_text='Specific location at venue (e.g., Søpavillonen)', max_length=200, verbose_name='Specific Location')),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='band.contact')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='band.venue')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-concert_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Artist Fee (DKK)')),
                ('booking_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Booking/Production Fee (DKK)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='VAT Amount (DKK)')),
                ('has_profit_sharing', models.BooleanField(default=False)),
                ('profit_sharing_percentage', models.IntegerField(blank=True, help_text='e.g., 80 for 80%', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Profit Sharing %')),
                ('profit_sharing_terms', models.TextField(blank=True, help_text="e.g., '80% after break even'")),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('bank_account', models.CharField(blank=True, help_text='Bank account for payment (reg: 7590 konto 1840092)', max_length=100)),
                ('tax_info', models.TextField(blank=True, help_text='CPR/CVR numbers for band members', verbose_name='Tax Information')),
                ('invoice_sent', models.BooleanField(default=False)),
                ('invoice_sent_date', models.DateField(blank=True, null=True)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_received_date', models.DateField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, help_text='Upload the signed contract PDF', null=True, upload_to='contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='band.event')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='TechnicalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_provided', models.BooleanField(default=True, verbose_name='Sound System Provided')),
                ('lights_provided', models.BooleanField(default=True, verbose_name='Lights Provided')),
                ('stage_provided', models.BooleanField(default=True, verbose_name='Stage Provided')),
                ('catering_provided', models.BooleanField(default=False, verbose_name='Catering/Forplejning Provided')),
                ('catering_details', models.TextField(blank=True, help_text='Details about catering')),
                ('hotel_rooms', models.IntegerField(default=0, help_text='Number of hotel rooms provided', validators=[django.core.validators.MinValueValidator(0)])),
                ('hotel_details', models.TextField(blank=True, help_text='Hotel details and location')),
                ('backline_provided', models.BooleanField(default=False, help_text='Does venue provide backline equipment?')),
                ('band_brings_equipment', models.BooleanField(default=True, verbose_name='Band Brings Own Equipment')),
                ('equipment_notes', models.TextField(blank=True, help_text='Details about equipment, backline, etc.')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special technical or logistical requirements')),
                ('soundcheck_time', models.TimeField(blank=True, null=True)),
                ('doors_open_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_requirements', to='band.event')),
            ],
            options={
                'verbose_name': 'Technical Requirements',
                'verbose_name_plural': 'Technical Requirements',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='band.venue'),
        ),
    ]
